### ISSUE TITLE
NullReference exception while doing kpm list

### ISSUE THREAD

**Issue by Praburaj** [aspnet/XRE#1093]
I run into this `NullReferenceException` while doing `kpm list` on `Logging` respository. 

```
C:\Users\testuser\Documents\GitHub\Logging\src\Microsoft.Framework.Logging>kpm list
List dependencies for Microsoft.Framework.Logging (C:\Users\testuser\Documents\GitHub\Logging\src\Microsoft.Framework.Logging\project.json)
[Target framework .NETFramework]
framework/Microsoft.CSharp 4.0.0.0
    -> Microsoft.Framework.Logging 1.0.0, Microsoft.Framework.Logging.Interfaces 1.0.0
Microsoft.Framework.Logging 1.0.0
    ->
Microsoft.Framework.Logging.Interfaces 1.0.0
    -> Microsoft.Framework.Logging 1.0.0
framework/mscorlib 4.0.0.0
    -> Microsoft.Framework.Logging 1.0.0, Microsoft.Framework.Logging.Interfaces 1.0.0
framework/System 4.0.0.0
    -> Microsoft.Framework.Logging 1.0.0, Microsoft.Framework.Logging.Interfaces 1.0.0
framework/System.Core 4.0.0.0
    -> Microsoft.Framework.Logging 1.0.0, Microsoft.Framework.Logging.Interfaces 1.0.0
[Target framework Asp.Net]
framework/Microsoft.CSharp 4.0.0.0
    -> Microsoft.Framework.Logging 1.0.0, Microsoft.Framework.Logging.Interfaces 1.0.0, Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921
Microsoft.Framework.Logging 1.0.0
    ->
Microsoft.Framework.Logging.Interfaces 1.0.0
    -> Microsoft.Framework.Logging 1.0.0
Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921
    -> Microsoft.Framework.Logging.Interfaces 1.0.0
framework/mscorlib 4.0.0.0
    -> Microsoft.Framework.Logging 1.0.0, Microsoft.Framework.Logging.Interfaces 1.0.0, Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921
framework/System 4.0.0.0
    -> Microsoft.Framework.Logging 1.0.0, Microsoft.Framework.Logging.Interfaces 1.0.0, Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921
framework/System.Core 4.0.0.0
    -> Microsoft.Framework.Logging 1.0.0, Microsoft.Framework.Logging.Interfaces 1.0.0, Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921
[Target framework Asp.NetCore]
Microsoft.Framework.Logging 1.0.0
    ->
Microsoft.Framework.Logging.Interfaces 1.0.0
    -> Microsoft.Framework.Logging 1.0.0
Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921
    -> Microsoft.Framework.Logging.Interfaces 1.0.0
System.Collections 4.0.10-beta-22231
    -> System.Linq 4.0.0-beta-22516
System.Collections.Concurrent 4.0.10-beta-22516
    -> Microsoft.Framework.Logging 1.0.0
System.ComponentModel 4.0.0-beta-22516
    -> Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921
System.Diagnostics.TraceSource 4.0.0-beta-22516
    -> Microsoft.Framework.Logging 1.0.0
System.Globalization 4.0.10-beta-22516
    -> Microsoft.Framework.Logging 1.0.0
System.IO 4.0.10-beta-22516
    -> Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921, System.Reflection 4.0.10-beta-22516
System.Linq 4.0.0-beta-22516
    -> Microsoft.Framework.Logging 1.0.0
System.Reflection 4.0.10-beta-22516
    -> Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921, System.Runtime.InteropServices 4.0.20-beta-22516
System.Reflection.Primitives 4.0.0-beta-22516
    -> System.Reflection 4.0.10-beta-22516, System.Runtime.InteropServices 4.0.20-beta-22516
System.Runtime 4.0.20-beta-22516
    -> Microsoft.Framework.Logging.Interfaces 1.0.0, Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921, System.Collections 4.0.10-beta-22231, System.Collections.Concurrent 4.0.10-beta-2251
System.Runtime.Extensions 4.0.10-beta-22516
    -> Microsoft.Framework.Logging.Interfaces 1.0.0, Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921
System.Runtime.Handles 4.0.0-beta-22516
    -> System.Runtime.InteropServices 4.0.20-beta-22516
System.Runtime.InteropServices 4.0.20-beta-22516
    -> Microsoft.Framework.Logging.Interfaces 1.0.0
System.Text.Encoding 4.0.10-beta-22231
    -> System.IO 4.0.10-beta-22516
System.Threading 4.0.10-beta-22516
    -> Microsoft.Framework.Logging 1.0.0
System.Threading.Tasks 4.0.10-beta-22516
    -> Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3-10921, System.Collections.Concurrent 4.0.10-beta-22516, System.IO 4.0.10-beta-22516, System.Threading 4.0.10-beta-22516
[Target framework .NETPortable]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Framework.Runtime.UnresolvedDependencyProvider.GetDescription(LibraryRange libraryRange, FrameworkName targetFramework)
   at Microsoft.Framework.Runtime.WalkContext.Resolve(Dictionary`2 resolvedItems, IEnumerable`1 providers, LibraryRange packageKey, FrameworkName frameworkName)
   at Microsoft.Framework.Runtime.WalkContext.<>c__DisplayClass1_0.<Walk>b__0(Node node)
   at Microsoft.Framework.Runtime.WalkContext.<>c__DisplayClass4_0.<ForEach>b__0(Node node, Int32 _)
   at Microsoft.Framework.Runtime.WalkContext.ForEach[TState](Node root, TState state, Func`3 visitor)
   at Microsoft.Framework.Runtime.WalkContext.ForEach(Node root, Action`1 visitor)
   at Microsoft.Framework.Runtime.WalkContext.Walk(IEnumerable`1 dependencyResolvers, String name, SemanticVersion version, FrameworkName frameworkName)
   at Microsoft.Framework.Runtime.DependencyWalker.Walk(String name, SemanticVersion version, FrameworkName targetFramework)
   at Microsoft.Framework.PackageManager.List.DependencyListOperation.CreateApplicationHostContext()
   at Microsoft.Framework.PackageManager.List.DependencyListCommand.Execute()
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_10.<Main>b__20()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)

C:\Users\testuser\Documents\GitHub\Logging\src\Microsoft.Framework.Logging>
```

**Comment by Praburaj** [comment]
@troydai

**Comment by troydai** [comment]
No repo. @Praburaj can you give it another try?

**Comment by Praburaj** [comment]
Can't repro with latest bits.
