### ISSUE TITLE
Project.Lock.Json files can get stale resulting in mystery build errors

### ISSUE THREAD

**Issue by MattGal** [aspnet/XRE#1241]
The very first time i set up a fresh hot machine with latest bits and cloned a project that had a project.lock.json, the .NET bits available had changed.  My project.lock.json file contained this:

```json
 "System.Runtime/4.0.20-beta-22516": {
      "contents": {
        "License.rtf": {},
        "System.Runtime.4.0.20-beta-22516.nupkg": {},
        "System.Runtime.4.0.20-beta-22516.nupkg.sha512": {},
        "System.Runtime.nuspec": {},
        "lib\\aspnetcore50\\System.Runtime.dll": {},
        "lib\\contract\\System.Runtime.dll": {},
        "lib\\net45\\System.Runtime.dll": {},
        "lib\\portable-wpa81+wp80+win80+net45+aspnetcore50\\System.Runtime.dll": {}
      }
```

... which no longer exists.  this leads to a confusing error (that doesn't currently send me to the .lock.json file) 

![image](https://cloud.githubusercontent.com/assets/7862010/6254695/8190c260-b75f-11e4-9dcf-e77cd83f8e4d.png)
.  This should automatically update when package restore is occurring for the solution (as it had to, as I was cloning to a totally fresh box)

**Comment by davidfowl** [comment]
It dies update in restore

**Comment by MattGal** [comment]
Maybe it died updating in KPM restore, not sure.  Ping me offline if you'd like to see my repro setup.

**Comment by kalluri-nb** [comment]
I'm not sure if this is related but Whenever i reopen the solution all the project.lock.json are cleared and   the external dependencies are not propagated to the referenced projects and the build results in errors. For ex If project B references Project A which has a dependency on System.Collections.Immutable. All the code in Project B which depends on System.Collections.Immutable errors out. This is happening only with external packages. I'm using VS 2015 CTP with kre-clr-win-x86.1.0.0-beta4-11094. And created the necessary junction directories for .kpm and .kre to .k folder.

**Comment by MattGal** [comment]
Another issue I've seen with stale project.lock.json comes from upgrading KRE.  I've seen this on several machines due to changes in format:

C:\GIT\DataPoint\Source\DataPoint.Web>kpm restore
Restoring packages for C:\GIT\DataPoint\Source\DataPoint.Web\project.json
----------
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.ReadLibrary(String property, JToken json)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.ReadObject[TItem](JObject json, Func`3 readItem)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.ReadLockFile(JObject cursor)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.Read(Stream stream)
   at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.Read(String filePath)
   at Microsoft.Framework.PackageManager.RestoreCommand.ReadLockFile(String projectLockFilePath)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass77_0.<<ExecuteCommand>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass89_0`1.<<ForEachAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__77.MoveNext()
----------
Restore failed
Value cannot be null.
Parameter name: source


... which can only be fixed by deleting / renaming project.lock.json.  It'd be much better to just blow away the file and re-write it if this happens versus crashing.

**Comment by davidfowl** [comment]
Closing this a dupe https://github.com/aspnet/XRE/issues/1220

**Comment by davidfowl** [comment]
As for the schema changes, lower your expectations as we are in active development and you are using nightly bits
