### ISSUE TITLE
Fail to locate project.json on IIS + Helios

### ISSUE THREAD

**Issue by troydai** [aspnet/XRE#1261]
The same scenario works with kre-clr-win-x86.1.0.0-beta4-11096 + Helios 11091.

```
Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 2/22/15 11:43:20 PM 
Event time (UTC): 2/23/15 7:43:20 AM 
Event ID: a2dd5b2e26a14427a4a33cba9bc6ddaf 
Event sequence: 1 
Event occurrence: 1 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/2/ROOT-1-130691510001749587 
    Trust level:  
    Application Virtual Path: / 
    Application Path: C:\0\wwwroot\ 
    Machine name: TDI-MACVM 
 
Process information: 
    Process ID: 5264 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\Test 
 
Exception information: 
    Exception type: TargetInvocationException 
    Exception message: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at kre.hosting.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at kre.clr.managed.EntryPoint.Execute(UInt32 argc, IntPtr argv)
   at IEntryPoint.Execute(UInt32 argc, IntPtr argv)
   at AspNet.Loader.Bootstrapper.<>c__DisplayClass1_0.<LoadApplicationNet45>b__0(Object _)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNet.Loader.Bootstrapper.LoadApplicationNet45(String appId, String appConfigPath, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData, Int32 loadAppDataSize, String runtimePackagePath, String appBasePath)
   at AspNet.Loader.Bootstrapper.LoadApplication(String appId, String appConfigPath, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData, Int32 loadAppDataSize)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Web.Hosting.ProcessHost.System.Web.Hosting.IProcessHostLite.ReportCustomLoaderError(String appId, Int32 hr, AppDomain newlyCreatedAppDomain)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironment(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)   at System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException)

Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at kre.host.Bootstrapper.Main(String[] args)

Unable to locate project.json
   at Microsoft.Framework.Runtime.DefaultHost.Initialize(DefaultHostOptions options, IServiceProvider hostServices)
   at Microsoft.Framework.Runtime.DefaultHost..ctor(DefaultHostOptions options, IServiceProvider hostServices)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)


```

**Comment by davidfowl** [comment]
What is KRE_APPBASe set to?

**Comment by suhasj** [comment]
+1 can repro this with KRE 1.0.0-beta4-11128. The `kre-app-base` in the web.config in the package created after `kpm bundle` is `..\approot\src\{AppName}`

**Comment by troydai** [comment]
@davidfowl @muratg @glennc anyone investigating this now?

**Comment by davidfowl** [comment]
Seems like no...

**Comment by muratg** [comment]
@Praburaj could you have a look?

**Comment by Praburaj** [comment]
@muratg sure.

**Comment by suhasj** [comment]
The issue does not repro for me with the latest bits. @troydai can you check if this still repros for your scenario

**Comment by Praburaj** [comment]
@troydai confirmed this does not reproduce anymore. Closing this down.
