### ISSUE TITLE
k test => not so helpful/wrong error message?

### ISSUE THREAD

**Issue by KevinDockx** [aspnet/XRE#1281]
Yesterday (after upgrading to the latest kvm), I ran k test - it presented me with this error:

```
PS C:\github\kevindockx\mvc\test\microsoft.aspnet.jsonpatch.test> k test
System.InvalidOperationException: project.lock.json must be loaded before resolving package path
   at Microsoft.Framework.Runtime.NuGetDependencyResolver.ResolvePackagePath(IPackagePathResolver defaultResolver, IEnum
erable`1 cacheResolvers, PackageInfo packageInfo)
   at Microsoft.Framework.Runtime.NuGetDependencyResolver.Initialize(IEnumerable`1 packages, FrameworkName targetFramewo
rk)
   at Microsoft.Framework.Runtime.WalkContext.Populate(FrameworkName frameworkName, IList`1 libraries)
   at Microsoft.Framework.Runtime.DependencyWalker.Walk(String name, SemanticVersion version, FrameworkName targetFramew
ork)
   at Microsoft.Framework.Runtime.DefaultHost.Initialize()
   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)?
```

The solution proved to be a to start with a kpm restore, and simply run k test again.  So there was something wrong, but the error message didn't really help :-)  Maybe it's a good idea to clarify the error message?

**Comment by davidfowl** [comment]
It's since been fixed
