### ISSUE TITLE
KPM Bundle fails with PathTooLongException after kpm restore

### ISSUE THREAD

**Issue by nicbourgoin** [aspnet/XRE#1290]
Too many nested node_modules files creates a PathTooLongException:

Duplicate of #821 but with KPM Bundle, here is the exception:

System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at Microsoft.Framework.PackageManager.Bundle.BundleOperations.Copy(String sourcePath, String targetPath, Func`2 shouldInclude)
   at Microsoft.Framework.PackageManager.Bundle.BundleProject.CopyProject(BundleRoot root, Project project, String targetPath, Boolean includeSource)
   at Microsoft.Framework.PackageManager.Bundle.BundleProject.EmitSource(BundleRoot root)
   at Microsoft.Framework.PackageManager.Bundle.BundleProject.Emit(BundleRoot root)
   at Microsoft.Framework.PackageManager.Bundle.BundleRoot.Emit()
   at Microsoft.Framework.PackageManager.Bundle.BundleManager.Bundle()
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_2.<Main>b__4()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)

**Comment by nicbourgoin** [comment]
Needed to change packExclude to bundleExclude.
