### ISSUE TITLE
Azure Deployment Issues - Could not load file or assembly / No service for type

### ISSUE THREAD

**Issue by sgtfrankieboy** [aspnet/XRE#1304]
I'm deploying my website using the GIT Deployment feature in Azure.

It will successfully complete the deployment but when I try to visit my website it's still showing the initial "This website has been successfully created" page.

Running `web.cmd` or `kestrel.cmd` manually will give me the following exception when using CoreCLR:

```
System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
```

Running them using CLR will give me this error:

```
System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.IServiceManifest' has been registered.
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Hosting.HostingServices.Import(IServiceProvider fallbackProvider)
   at Microsoft.AspNet.Hosting.HostingServices.Create(IServiceProvider fallbackServices, IConfiguration configuration)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
```

I've tried redeploying/delete package cache.

I'm running SDK version `1.0.0-beta4-11158`.

My `project.json`:

```JSON
{
	"webroot": "wwwroot",
	"version": "1.0.0-*",
	"dependencies": {
		"Kestrel": "1.0.0-*",
		"Microsoft.AspNet.Diagnostics": "1.0.0-*",
		"Microsoft.AspNet.Hosting": "1.0.0-*",
		"Microsoft.AspNet.Mvc": "6.0.0-*",
		"Microsoft.AspNet.Server.WebListener": "1.0.0-*",
		"Microsoft.AspNet.StaticFiles": "1.0.0-*",
		"Microsoft.Net.Http.Client": "1.0.0-*"
	},
	"commands": {
		"web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
		"kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5004"
	},
	"frameworks": {
		"aspnet50": {
			"dependencies": {
				"Microsoft.Net.Http.Client": "1.0.0-*"
			}
		},
		"aspnetcore50": {
			"dependencies": {
				"Microsoft.Net.Http.Client": "1.0.0-*"
			}
		}
	},
    "bundleExclude": [
        "node_modules",
        "bower_components",
        "**.kproj",
        "**.user",
        "**.vspscc"
    ],
    "exclude": [
        "wwwroot",
        "node_modules",
        "bower_components"
    ]
}
```

**Comment by sgtfrankieboy** [comment]
I found out what the issue is. The deployment script uses the default kvm.ps1 script which means it only fetches from nuget.org (beta1, beta2).

Uploading the dev version of kvm.ps1 manually and setting `SCM_KVM_PS_PATH` to point to the file did manage to download the file, but is now telling that `kpm` is not recognized as an internal or external command.


```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Using custom deployment setting for SCM_KRE_VERSION custom value is '1.0.0-beta4-11158'.
Using custom deployment setting for SCM_KVM_PS_PATH custom value is 'D:\home\site\kvm.ps1'.
Handling ASP.NET 5 Web Application deployment.
kre-clr-win-x86.1.0.0-beta4-11158 already installed.
Adding D:\local\UserProfile\.k\runtimes\kre-clr-win-x86.1.0.0-beta4-11158\bin to process PATH
'kpm' is not recognized as an internal or external command,
An error has occurred during web site deployment.
operable program or batch file.
```

however when looking into the bin directory of the runtime, it clearly shows a file called `kpm.cmd`.

**Comment by glennc** [comment]
@troydai Can you check on the state of our Kudu integration, and perhaps see why setting the path appears to be failing?

**Comment by troydai** [comment]
@sgtfrankieboy,  you don't need to carry `kvm.ps1` with your side any more. Windows Azure Websites now carries the last `kvm.ps1`. Also, the parameter `SCM_KRE_VERSION` is retired. __Kudu__ do not read from it anymore, instead it reads `global.json`'s `sdk` property`

```
{
    "sources": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-beta4-11181"
    }
}
```
