### ISSUE TITLE
`k build` does not work in beta3

### ISSUE THREAD

**Issue by conniey** [aspnet/XRE#1333]
I have a library that I want to build in ASP.NET vNext, but when I run [`k build`](https://github.com/aspnet/Home/wiki/Command-Line#k-command), it gives me an InvalidOperationException saying that it can't execute the command `build`.
The sample code I tried to build was the sample from XRE:  https://github.com/aspnet/XRE/tree/dev/samples/HelloShared

```
E:\git\repos\xre> kvm upgrade
Determining latest version
Downloading kre-clr-win-x86.1.0.0-beta3 from https://www.nuget.org/api/v2
Unpacking to C:\Users\conniey\.k\runtimes\temp
Installing to C:\Users\conniey\.k\runtimes\kre-clr-win-x86.1.0.0-beta3
Adding C:\Users\conniey\.k\runtimes\kre-clr-win-x86.1.0.0-beta3\bin to process PATH
Adding C:\Users\conniey\.k\runtimes\kre-clr-win-x86.1.0.0-beta3\bin to user PATH
Setting alias 'default' to 'kre-clr-win-x86.1.0.0-beta3'

E:\git\repos\xre\samples\HelloShared>kvm list

Active Version     Runtime Architecture Location                     Alias
------ -------     ------- ------------ --------                     -----
       1.0.0-beta3 clr     x86          C:\Users\conniey\.k\runtimes default

E:\git\repos\xre\samples\HelloShared>k build
System.InvalidOperationException: Unable to load application or execute command
'build'.
   at Microsoft.Framework.ApplicationHost.Program.ThrowEntryPointNotfoundException(DefaultHost host, String applicationName, Exception innerException)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
```

**Comment by davidfowl** [comment]
k build hasn't worked since 0.1-alpha3, it's kpm pack now.

**Comment by conniey** [comment]
Is the wiki going to be updated? https://github.com/aspnet/Home/wiki/Command-Line#k-command says that it should

**Comment by davidfowl** [comment]
Tweaked it /cc @glennc
