### ISSUE TITLE
AppDomains don't work (aspnet50)

### ISSUE THREAD

**Issue by bricelam** [aspnet/XRE#985]
The following code...
```C#
AppDomain.CreateDomain("MyDomain");
```

...throws the following exception.

```
System.TypeLoadException: The domain manager specified by the host could not be instantiated. ---> System.IO.FileNotFoundException: Could not load file or assembly 'klr.net45.managed' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
   at System.AppDomain.CreateAppDomainManager()
   --- End of inner exception stack trace ---
   at System.AppDomain.CreateAppDomainManager()
   at System.AppDomain.Setup(Object arg)
   at System.AppDomain.nCreateDomain(String friendlyName, AppDomainSetup setup, Evidence providedSecurityInfo, Evidence creatorsSecurityInfo, IntPtr parentSecurityDescriptor)
   at System.AppDomainManager.CreateDomainHelper(String friendlyName, Evidence securityInfo, AppDomainSetup appDomainInfo)
   at System.AppDomainManager.CreateDomain(String friendlyName, Evidence securityInfo, AppDomainSetup appDomainInfo)
   at System.AppDomain.InternalCreateDomain(String friendlyName, Evidence securityInfo, AppDomainSetup info)
   at System.AppDomain.CreateDomain(String friendlyName, Evidence securityInfo, AppDomainSetup info)
   at System.AppDomain.CreateDomain(String friendlyName)
```

**Comment by davidfowl** [comment]
For now. I'm sure there's a way to make this work without having to null out the appdomain manager. We just need to set the right flags or something like that.

**Comment by davidfowl** [comment]
I believe this works now without having to specify the domain manager as empty string

**Comment by davidfowl** [comment]
Just tried it and I'm getting a new error:

```C#
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at DomainManager.BindApplicationMain(ApplicationMainInfo& info)
   at DomainManager.InitializeNewDomain(AppDomainSetup appDomainInfo)
   at System.AppDomain.CreateAppDomainManager()
   at System.AppDomain.Setup(Object arg)
   at System.AppDomain.nCreateDomain(String friendlyName, AppDomainSetup setup, Evidence providedSecurityInfo, Evidence creatorsSecurityInfo, IntPtr p
arentSecurityDescriptor)
   at System.AppDomainManager.CreateDomainHelper(String friendlyName, Evidence securityInfo, AppDomainSetup appDomainInfo)
   at System.AppDomainManager.CreateDomain(String friendlyName, Evidence securityInfo, AppDomainSetup appDomainInfo)
   at System.AppDomain.InternalCreateDomain(String friendlyName, Evidence securityInfo, AppDomainSetup info)
   at System.AppDomain.CreateDomain(String friendlyName, Evidence securityInfo, AppDomainSetup info)
   at System.AppDomain.CreateDomain(String friendlyName)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\davifowl\Documents\Visual Studio 14\Projects\WebApplication7\src\ConsoleApp1\Program.cs:line
 10
```

We'll have to clean up our AppDomainManager so make it handle this.

**Comment by davidfowl** [comment]
Fixed in https://github.com/aspnet/XRE/commit/16fd19ac4ce951ee426ee40ee887e32806663436
